FROM golang:latest

RUN go get -u golang.org/x/tools/cmd/goimports
RUN go get -u github.com/kisielk/errcheck
RUN go get -u golang.org/x/lint/golint
RUN go get -u github.com/client9/misspell/cmd/misspell
RUN go get -u github.com/tockins/realize
