// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type User struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*GetUserRequest)(nil), "proto.GetUserRequest")
	proto.RegisterType((*User)(nil), "proto.User")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x8f, 0x31, 0x4b, 0xc4, 0x40,
	0x10, 0x85, 0x49, 0x72, 0x27, 0x38, 0x27, 0x87, 0x0c, 0x08, 0xe1, 0xb0, 0x08, 0xa9, 0xae, 0xca,
	0x82, 0x22, 0x36, 0xda, 0xd8, 0x5c, 0x63, 0x15, 0xb1, 0xb1, 0x91, 0xb9, 0x64, 0x58, 0x17, 0x2e,
	0xbb, 0xeb, 0xee, 0x46, 0x41, 0xb1, 0xf1, 0x2f, 0xf8, 0xd3, 0xfc, 0x0b, 0xfe, 0x10, 0xd9, 0x8d,
	0x8d, 0x57, 0xbd, 0xc7, 0xb7, 0x6f, 0xe7, 0xf1, 0x00, 0x46, 0xcf, 0xae, 0xb1, 0xce, 0x04, 0x83,
	0xf3, 0x24, 0xab, 0x53, 0x69, 0x8c, 0xdc, 0xb1, 0x20, 0xab, 0x04, 0x69, 0x6d, 0x02, 0x05, 0x65,
	0xb4, 0x9f, 0x42, 0x75, 0x05, 0xcb, 0x0d, 0x87, 0x7b, 0xcf, 0xae, 0xe5, 0xe7, 0x91, 0x7d, 0xc0,
	0x25, 0xe4, 0xaa, 0x2f, 0xb3, 0x2a, 0x5b, 0xcf, 0xdb, 0x5c, 0xf5, 0xf5, 0x15, 0xcc, 0xe2, 0xf3,
	0x3e, 0x47, 0x84, 0x99, 0xa6, 0x81, 0xcb, 0xbc, 0xca, 0xd6, 0x87, 0x6d, 0xf2, 0x78, 0x0c, 0x05,
	0x49, 0x2e, 0x8b, 0x14, 0x8a, 0xf6, 0xec, 0x16, 0x16, 0xf1, 0xf7, 0x1d, 0xbb, 0x17, 0xd5, 0x31,
	0x5e, 0x43, 0xb1, 0xe1, 0x80, 0x27, 0x53, 0x7b, 0xf3, 0xbf, 0x7a, 0xb5, 0xf8, 0xc3, 0x91, 0xd5,
	0xf8, 0xf9, 0xfd, 0xf3, 0x95, 0x1f, 0x21, 0x88, 0xb8, 0x49, 0xbc, 0xab, 0xfe, 0xe3, 0xe6, 0xf2,
	0xe1, 0x42, 0xaa, 0xf0, 0x34, 0x6e, 0x9b, 0xce, 0x0c, 0x42, 0x1a, 0x4f, 0x92, 0x5e, 0x49, 0x38,
	0xa6, 0x9d, 0x7a, 0xe3, 0x47, 0x4f, 0x83, 0x8d, 0x4b, 0x7b, 0xb2, 0x81, 0x9d, 0x90, 0xce, 0x76,
	0x22, 0x5d, 0xdc, 0x1e, 0x24, 0x39, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x5a, 0x18, 0x21, 0x9d,
	0x20, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Get(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Get(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/proto.UserService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Get(context.Context, *GetUserRequest) (*User, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Get(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _UserService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
